name: CI
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  build:
    name: Build and test project with Java ${{ matrix.java-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ['8', '11', '17']
    steps:
      - uses: actions/checkout@v4
      - name: Java ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin
          cache: gradle
      - name: Run tests
        run: ./gradlew clean test
